### ISSUE TITLE
10 bonnes réponses -> Score = 37/10

### ISSUE THREAD

**Issue by sputier** [Listeriaa/kaamelott-v2#1]
Hello ! 

Je suis tombé sur ton petit jeu en cherchant une API Kaamelott, et en bon fan, je me suis senti obligé d'essayer... Et il se trouve que j'ai obtenu un score des plus étranges : 37/10. Résultat, dans tous les cas, **💩 C'est d'la merde. 💩**

![image](https://user-images.githubusercontent.com/1064551/148840881-4881d8de-185c-4c88-acdb-8b1b0fbae724.png)

En jetant un oeil à ton CV, j'ai remarqué que tu étais étudiante. Du coup, tu préfères peut-être chercher la source du problème par toi-même... Si c'est bien le cas et que tu as besoin d'un coup de main, je t'aiderai volontiers. Dans le cas contraire, fais moi signe, je jetterai un oeil pour passer une PR.

Bonne soirée !

Edit : Je viens de voir que tu avais traité ce sujet [sur la branche de dev](https://github.com/Listeriaa/kaamelott-v2/commit/a30ed771903058ea44d85ceab10f892567f73aed) 👍 Libre à toi de fermer l'issue, du coup 😉

**Comment by Listeriaa** [comment]
Bonjour,
Désolée, j'ai pas eu le temps de te répondre ce matin.

Effectivement, j'ai repris tout mon code que j'avais fait y'a quelques mois, pour l'optimiser et j'en ai profité pour régler le problème, mais je n'ai pas pris le temps de le deployer -_-

Merci pour ton message en tout cas, je vais aller mettre la version a jour en ligne^^

**Comment by sputier** [comment]
Salut ! 
Je me permets de repasser par là parce que j'ai noté un nouveau souci suite à la correction que tu as apportée : même si j'ai tout bon, je n'ai que 9/10 😅 Probablement rien de bien grave, ceci dit. 

![image](https://user-images.githubusercontent.com/1064551/150866411-ed7e7f89-d690-47e6-b875-d0373c69ed86.png)

Si je peux me permettre, n'hésite pas à creuser la question des tests unitaires (valable aussi bien pour le front que le back). Ca pourra t'éviter un certain nombre de problèmes, et c'est une véritable bonne habitude. Autant la prendre le plus tôt possible 😉 

Bonne soirée, et bon courage sur le chemin de l'apprentissage !
